# Availabl commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget /bin/sh -c "sleep 10 && /etc/profiles/per-user/hest/bin/sketchybar --reload"',
  'exec-and-forget /bin/sh -c "sleep 10 && ~/.config/sketchybar/scripts/media-stream.sh"',
  'exec-and-forget open -a Tailscale',
]

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true


exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  '/etc/profiles/per-user/hest/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# App specficics 

[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.github.th-ch.youtube-music'
run = ['move-node-to-workspace 4']


# ToDO set layout v_accordioin when restrictions are lifted:
# https://github.com/nikitabobko/AeroSpace/issues/20
[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = ['layout tiling', 'move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['layout tiling', 'move-node-to-workspace 1']

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 10
outer.bottom = 10
outer.top = 5
outer.right = 10


[key-mapping]
preset = 'qwerty'

[mode.main.binding]

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-f = [
  'layout floating tiling',
  'mode main',
] # Toggle between floating and tiling layout


alt-h = 'exec-and-forget /bin/sh -c "/run/current-system/sw/bin/aerospace focus --boundaries-action fail left || /run/current-system/sw/bin/aerospace workspace prev"'
alt-l = 'exec-and-forget /bin/sh -c "/run/current-system/sw/bin/aerospace focus --boundaries-action fail right || /run/current-system/sw/bin/aerospace workspace next"'

alt-j = 'focus down --boundaries-action wrap-around-the-workspace'
alt-k = 'focus up --boundaries-action wrap-around-the-workspace'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'


# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
alt-shift-semicolon = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']                # reset layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']
