#!/usr/bin/env lua

local script_path = debug.getinfo(1, "S").source:match("@?(.*[/\\])")
package.path = package.path .. ";" .. script_path .. "?.lua;" .. script_path .. "?/init.lua"

require("helpers")
require("init")
