return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      opts.ensure_installed = opts.ensure_installed or {}
      vim.list_extend(opts.ensure_installed, { "c_sharp", "html", "razor" })
    end,
  },
}

-- 'bash',
-- 'c',
-- 'cmake',
-- 'c_sharp',
-- 'diff',
-- 'dockerfile',
-- 'dtd',
-- 'eex',
-- 'elixir',
-- 'fish',
-- 'fsharp',
-- 'gitattributes',
-- 'gitcommit',
-- 'gitignore',
-- 'git_config',
-- 'git_rebase',
-- 'gleam',
-- 'go',
-- 'gomod',
-- 'gosum',
-- 'gowork',
-- 'heex',
-- 'html',
-- 'java',
-- 'javascript',
-- 'jsdoc',
-- 'json',
-- 'json5',
-- 'kotlin',
-- 'lua',
-- 'luadoc',
-- 'luap',
-- 'markdown',
-- 'markdown_inline',
-- 'nix',
-- 'nu',
-- 'printf',
-- 'python',
-- 'query',
-- 'razor',
-- 'regex',
-- 'ron',
-- 'rust',
-- 'scala',
-- 'toml',
-- 'tsx',
-- 'typescript',
-- 'vim',
-- 'vimdoc',
-- 'xml',
-- 'yaml',
