return {
  -- "ThePrimeagen/harpoon",
  -- branch = "harpoon2",
  -- opts = {
  --   menu = {
  --     width = vim.api.nvim_win_get_width(0) - 4,
  --   },
  --   settings = {
  --     save_on_toggle = true,
  --     sync_on_ui_close = true,
  --   },
  -- },
  -- keys = function()
  --   local keys = {
  --     {
  --       "<leader>H",
  --       function()
  --         require("harpoon"):list():add()
  --       end,
  --       desc = "Harpoon File",
  --     },
  --     {
  --       "<leader>h",
  --       function()
  --         local harpoon = require("harpoon")
  --         harpoon.ui:toggle_quick_menu(harpoon:list())
  --       end,
  --       desc = "Harpoon Quick Menu",
  --     },
  --   }
  --
  --   local wk = require("which-key")
  --   for i = 1, 9 do
  --     wk.add({
  --       "<leader>" .. i,
  --       function()
  --         require("harpoon"):list():select(i)
  --       end,
  --       hidden = true,
  --       -- cond = function()
  --       --   if require("harpoon"):list():get(i) then
  --       --     return true
  --       --   end
  --       --   return false
  --       -- end,
  --       desc = function()
  --         local item = require("harpoon"):list():get(i)
  --         if item then
  --           return item.value
  --         end
  --         return ""
  --       end,
  --     })
  --   end
  --   return keys
  -- end,
}
